import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const monasans = localFont({
  src: [
    {
      path: "./assets/fonts/MonaSans-Medium.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./assets/fonts/MonaSans-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./assets/fonts/MonaSans-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Pitlane Fever",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${monasans.className} min-h-screen bg-base-100`}>
        {children}
      </body>
    </html>
  );
}
